frontend/web/webserver/config/routes.rb
Rails.application.routes.draw do
  get 'overview/update'
  root 'location#list'

  get 'graph/list'
  get 'overview/list'
  post 'overview/update'
  get 'settings/edit'
  post 'settings/update'

  get 'device/list'
  get 'location/list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

frontend/web/webserver/app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  include JsonHelper
  include OverviewHelper

  def update
      if (params["ids"] != nil)
        Rails.configuration.ids = params["ids"].split(",").map(&:strip)
      end
      Rails.configuration.startTime = params["startTime"]
      Rails.configuration.endTime = params["endTime"]
    
      redirect_to overview_list_path
      return
  end

  def list
    if (Rails.configuration.ids == nil || Rails.configuration.ids.empty?)
      @ids = getAllDevices
    else
      @ids = Rails.configuration.ids
    end
    if (Rails.configuration.startTime == nil)
      @startTime = "2018-10-13 00:00:00"
    else
      @startTime = Rails.configuration.startTime
    end
    if (Rails.configuration.endTime == nil)
      @endTime = "2999-01-01 00:00:00"
    else
      @endTime = Rails.configuration.endTime
    end
    begin
      response = {"type" => "ListOverview",
              "data" => [{"loadedTime" => 3,
              "emptyTime" => 4}]}
      response = getJsonForType({:type => "ListOverview",
                    "devices" => @ids,
                    "start" => @startTime,
                    "end" => @endTime})
    rescue Errno::EHOSTUNREACH
      redirect_to settings_edit_path
      return
    end

    if response["type"] != "ListOverview"
      raise "Wrong return type"
    else
      @overviewEntries = response["data"]
    end
    @overviewEntries.each do |entry|
    entry["time"] = entry["emptyTime"] + entry["loadedTime"]
    entry["percentage"] = entry["loadedTime"] * 100 / entry["time"]
  end

  end
end

frontend/web/webserver/app/helpers/overview_helper.rb
module OverviewHelper
    def getAllDevices
      response = getJsonForType({"type" => "ListDevices",
                    "start" => nil,
                    "end" => nil,
                    "location" => nil})
    if response["type"] != "ListDevices"
      raise "Wrong List type"
    else
      devices = response["data"]
    end
    return devices.map! { |device| device.first[1] }
  end

end

frontend/web/webserver/app/views/overview/list.html.erb
<h1>Overview</h1>

  <%= form_with url: overview_update_path do |form| %>
    <%= form.text_field :ids, :value => @ids.join(", ") %>
    <%= form.text_field :startTime, :value => @startTime %>
    <%= form.text_field :endTime, :value => @endTime %>
    <%= form.submit %>
  <% end %>


<table>
  <tr><th>ID</th><th>Zeit (sek)</th><th>beladen (sek)</th><th>unbeladen (sek)</th><th>% der beladen Zeit</th></tr>
  <% @overviewEntries.each.with_index do |overview, index| %>
    <tr>
      <td><%= overview["id"] %></td>
      <td><%= overview["time"] %></td>
      <td><%= overview["loadedTime"] %></td>
      <td><%= overview["emptyTime"] %></td>
      <td><%= overview["percentage"] %></td>
    </tr>
  <% end %>
</table>

frontend/web/webserver/app/views/overview/update.html.erb
<h1>Overview#update</h1>
<p>Find me in app/views/overview/update.html.erb</p>